spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf8&characte
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapping/*.xml
#thymeleaf:
                   ##       cache: false
                   ##       prefix: classpath:/templates/views/
                   ##       suffix: .html
                   ##       encoding: UTF-8
                   ###       content-type: text/html
                   ##       servlet:
                   ##          content-type: text/html
                   ##       mode: HTML5